/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MENU;
import java.awt.event.KeyEvent;
import javax.swing.*;


/**
 *
 * @author aliid
 */
public class mainMenu extends javax.swing.JFrame {
foodMenu menu = new foodMenu();
    /**
     * Creates new form Menu
     */
    public mainMenu() {
//        konfirmasiPembayaranAktif();
        initComponents();
        nonaktif();
        
        pembayaran.addItem("Dana");
        pembayaran.addItem("Ovo");
        pembayaran.addItem("Transfer Bank");
        pembayaran.addItem("Cash");
    }

    void nonaktif(){
        bayar.setEnabled(false);
        namaMenu.setEnabled(false);
        harga.setEnabled(false);
        opsi1.setEnabled(false);
        Opsi2.setEnabled(false);
        Opsi3.setEnabled(false);
        Opsi4.setEnabled(false);
        Opsi5.setEnabled(false);
        Opsi6.setEnabled(false);
        Opsi7.setEnabled(false);
        Opsi8.setEnabled(false);
        Opsi9.setEnabled(false);
        Opsi10.setEnabled(false);
        Opsi11.setEnabled(false);
        Opsi10.setEnabled(false);
        Opsi12.setEnabled(false);
        
        
        namaPembeli.setEnabled(false);
        jumlahBeli.setEnabled(false);
        pembayaran.setEnabled(false);
        diskon.setEnabled(false);
        ppn.setEnabled(false);
        totalHarga.setEnabled(false);
       
        bayar.setEnabled(false);
        jDonasi.setEnabled(false);
        uangBayar.setEnabled(false);
        kembalian.setEnabled(false);
    }
    
    void konfirmasiPembayaranAktif(){
        pembayaran.setEnabled(true);
        uangBayar.setEnabled(true);
    }
   
    void disablemenu(){
        burger.setEnabled(false);
        kopi.setEnabled(false);
        juss.setEnabled(false);
        friedChicken.setEnabled(false);
        friedFries.setEnabled(false);
        mie.setEnabled(false);
        nasi.setEnabled(false);
        soda.setEnabled(false);
        pizza.setEnabled(false);
    }
    
    
    void bersih(){
        noDonasi.setSelected(true);
        donasi.clearSelection();
        Size.clearSelection();
        pembayaran.setSelectedItem("PILIH");
        harga.setText("");
        diskon.setText("");
        totalHarga.setText("");
        jDonasi.setText("0");
        jumlahBeli.setText("");
        ppn.setText("0");
        namaPembeli.setText("");
        namaMenu.setText("");
        uangBayar.setText("");
        kembalian.setText("");
        
        bdonasi.setSelected(false);
        
        
        burger.setEnabled(true);
        kopi.setEnabled(true);
        juss.setEnabled(true);
        friedChicken.setEnabled(true);
        friedFries.setEnabled(true);
        mie.setEnabled(true);
        nasi.setEnabled(true);
        soda.setEnabled(true);
        pizza.setEnabled(true);
        uangBayar.setEnabled(true);
    }
    
    Void bersihkanOpsi(){
        opsi1.setSelected(false);
        Opsi2.setSelected(false);
        Opsi3.setSelected(false);
        Opsi4.setSelected(false);
        Opsi5.setSelected(false);
        Opsi6.setSelected(false);
        Opsi7.setSelected(false);
        Opsi8.setSelected(false);
        Opsi9.setSelected(false);
        Opsi10.setSelected(false);
        Opsi11.setSelected(false);
        Opsi12.setSelected(false);
        
        Size.clearSelection();
        jumlahBeli.setText("0");
        harga.setText("");
        
        
    return null;
    }
    
    void dataPembeliaktif(){
        namaPembeli.setEnabled(true);
        jumlahBeli.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        donasi = new javax.swing.ButtonGroup();
        Size = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        burger = new javax.swing.JButton();
        kopi = new javax.swing.JButton();
        juss = new javax.swing.JButton();
        pizza = new javax.swing.JButton();
        friedChicken = new javax.swing.JButton();
        friedFries = new javax.swing.JButton();
        soda = new javax.swing.JButton();
        nasi = new javax.swing.JButton();
        mie = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jumlahBeli = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        namaPembeli = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        namaMenu = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Opsi3 = new javax.swing.JCheckBox();
        Opsi2 = new javax.swing.JCheckBox();
        Opsi4 = new javax.swing.JCheckBox();
        Opsi5 = new javax.swing.JCheckBox();
        opsi1 = new javax.swing.JCheckBox();
        Opsi6 = new javax.swing.JCheckBox();
        Opsi7 = new javax.swing.JCheckBox();
        Opsi8 = new javax.swing.JCheckBox();
        Opsi9 = new javax.swing.JCheckBox();
        Opsi10 = new javax.swing.JCheckBox();
        Opsi11 = new javax.swing.JCheckBox();
        Opsi12 = new javax.swing.JCheckBox();
        buttonOpsiSelesai = new javax.swing.JButton();
        harga = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bdonasi = new javax.swing.JRadioButton();
        noDonasi = new javax.swing.JRadioButton();
        jDonasi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        totalHarga = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ppn = new javax.swing.JTextField();
        bayar = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        diskon = new javax.swing.JTextField();
        pembayaran = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        uangBayar = new javax.swing.JTextField();
        kembalian = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        burger.setBackground(new java.awt.Color(134, 182, 246));
        burger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/burger.png"))); // NOI18N
        burger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                burgerMouseClicked(evt);
            }
        });
        burger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                burgerActionPerformed(evt);
            }
        });

        kopi.setBackground(new java.awt.Color(134, 182, 246));
        kopi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/coffee-cup.png"))); // NOI18N
        kopi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kopiMouseClicked(evt);
            }
        });
        kopi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kopiActionPerformed(evt);
            }
        });
        kopi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kopiKeyPressed(evt);
            }
        });

        juss.setBackground(new java.awt.Color(134, 182, 246));
        juss.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/drink.png"))); // NOI18N
        juss.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jussMouseClicked(evt);
            }
        });
        juss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jussActionPerformed(evt);
            }
        });

        pizza.setBackground(new java.awt.Color(134, 182, 246));
        pizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pizza.png"))); // NOI18N
        pizza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pizzaMouseClicked(evt);
            }
        });
        pizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pizzaActionPerformed(evt);
            }
        });

        friedChicken.setBackground(new java.awt.Color(134, 182, 246));
        friedChicken.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/fried-chicken.png"))); // NOI18N
        friedChicken.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                friedChickenMouseClicked(evt);
            }
        });
        friedChicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                friedChickenActionPerformed(evt);
            }
        });

        friedFries.setBackground(new java.awt.Color(134, 182, 246));
        friedFries.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/fries.png"))); // NOI18N
        friedFries.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                friedFriesMouseClicked(evt);
            }
        });
        friedFries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                friedFriesActionPerformed(evt);
            }
        });

        soda.setBackground(new java.awt.Color(134, 182, 246));
        soda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/soft-drink.png"))); // NOI18N
        soda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sodaMouseClicked(evt);
            }
        });
        soda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sodaActionPerformed(evt);
            }
        });

        nasi.setBackground(new java.awt.Color(134, 182, 246));
        nasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/rice.png"))); // NOI18N
        nasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nasiMouseClicked(evt);
            }
        });
        nasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nasiActionPerformed(evt);
            }
        });

        mie.setBackground(new java.awt.Color(134, 182, 246));
        mie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/ramen.png"))); // NOI18N
        mie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mieMouseClicked(evt);
            }
        });
        mie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mieActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setText("WhiteBeard Food");

        jPanel3.setBackground(new java.awt.Color(180, 212, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Pembelian"));

        jLabel4.setText("Jumlah   :");

        jumlahBeli.setText("0");
        jumlahBeli.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jumlahBeliFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jumlahBeliFocusLost(evt);
            }
        });
        jumlahBeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jumlahBeliMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jumlahBeliMousePressed(evt);
            }
        });
        jumlahBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahBeliActionPerformed(evt);
            }
        });
        jumlahBeli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jumlahBeliKeyPressed(evt);
            }
        });

        jLabel9.setText("Pembeli :");

        jLabel10.setText("Nama Menu :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel4))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(namaMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(namaPembeli)
                    .addComponent(jumlahBeli))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(namaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(namaPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumlahBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(180, 212, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail Pesanan"));

        Size.add(Opsi3);
        Opsi3.setText("Opsi");
        Opsi3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opsi3ActionPerformed(evt);
            }
        });

        Size.add(Opsi2);
        Opsi2.setText("Opsi");
        Opsi2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Opsi2FocusLost(evt);
            }
        });
        Opsi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opsi2ActionPerformed(evt);
            }
        });
        Opsi2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Opsi2KeyPressed(evt);
            }
        });

        Opsi4.setText("Opsi");

        Opsi5.setText("Opsi");

        Size.add(opsi1);
        opsi1.setText("Opsi");
        opsi1.setToolTipText("");
        opsi1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                opsi1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                opsi1FocusLost(evt);
            }
        });
        opsi1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opsi1MouseClicked(evt);
            }
        });
        opsi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opsi1ActionPerformed(evt);
            }
        });
        opsi1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                opsi1KeyPressed(evt);
            }
        });

        Opsi6.setText("Opsi");

        Opsi7.setText("Opsi");

        Opsi8.setText("Opsi");

        Opsi9.setText("Opsi");

        Opsi10.setText("Opsi");
        Opsi10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opsi10ActionPerformed(evt);
            }
        });

        Opsi11.setText("Opsi");

        Opsi12.setText("Opsi ");

        buttonOpsiSelesai.setText("SELESAI");
        buttonOpsiSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOpsiSelesaiActionPerformed(evt);
            }
        });
        buttonOpsiSelesai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buttonOpsiSelesaiKeyPressed(evt);
            }
        });

        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });

        jLabel1.setText("Harga    :");

        donasi.add(bdonasi);
        bdonasi.setText("Donasi");
        bdonasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdonasiActionPerformed(evt);
            }
        });

        donasi.add(noDonasi);
        noDonasi.setText("Tidak Donasi");
        noDonasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noDonasiActionPerformed(evt);
            }
        });

        jDonasi.setText("0");
        jDonasi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jDonasiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jDonasiFocusLost(evt);
            }
        });
        jDonasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDonasiActionPerformed(evt);
            }
        });

        jLabel5.setText("Donasi   :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 238, Short.MAX_VALUE)
                        .addComponent(Opsi4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(harga)
                                .addGap(35, 35, 35)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(opsi1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Opsi2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(buttonOpsiSelesai)
                                            .addComponent(noDonasi))
                                        .addGap(55, 55, 55))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jDonasi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Opsi8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Opsi7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Opsi9, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Opsi11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Opsi12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Opsi5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Opsi10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bdonasi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Opsi3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(Opsi6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opsi1)
                    .addComponent(Opsi4)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Opsi2)
                    .addComponent(Opsi5)
                    .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Opsi3)
                            .addComponent(Opsi6)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(bdonasi)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Opsi7)
                            .addComponent(Opsi10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Opsi11)
                            .addComponent(Opsi8)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(noDonasi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDonasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(Opsi12)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Opsi9)
                            .addComponent(buttonOpsiSelesai))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel4.setBackground(new java.awt.Color(180, 212, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Konfirmasi Pembelian"));

        jLabel2.setText("Total Harga");

        jLabel6.setText("PPN");

        ppn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppnActionPerformed(evt);
            }
        });

        bayar.setText("BAYAR");
        bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarActionPerformed(evt);
            }
        });

        jButton13.setText("KELUAR");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        pembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH" }));
        pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembayaranActionPerformed(evt);
            }
        });

        jLabel8.setText("Diskon");

        jLabel7.setText("Pembayaran");

        jLabel11.setText("Uang Bayar:");

        jLabel12.setText("Uang Kembalian:");

        uangBayar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                uangBayarMouseEntered(evt);
            }
        });
        uangBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uangBayarActionPerformed(evt);
            }
        });
        uangBayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                uangBayarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(diskon, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2))
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ppn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(uangBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jButton13)
                .addGap(133, 133, 133)
                .addComponent(bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(ppn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(uangBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(diskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(totalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bayar)
                    .addComponent(jButton13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Logo DANA -  (Koleksilogo.com) (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mie, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(burger, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(friedChicken, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(kopi, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(juss, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(friedFries, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pizza, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(soda, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nasi, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(247, 247, 247))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kopi)
                            .addComponent(burger))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(friedFries)
                            .addComponent(friedChicken)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(juss)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pizza)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nasi)
                            .addComponent(mie)
                            .addComponent(soda))
                        .addGap(31, 31, 31)
                        .addComponent(jLabel13)))
                .addGap(7, 7, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Opsi10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opsi10ActionPerformed
        
    }//GEN-LAST:event_Opsi10ActionPerformed

    private void burgerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_burgerMouseClicked
        JComponent[] opsiaktif = {opsi1, Opsi2, Opsi3, Opsi4, Opsi5, Opsi6, Opsi7, Opsi8, Opsi9};
        JComponent[] opsiNoAktif = {Opsi10,Opsi11,Opsi12};
        for (JComponent opsi : opsiaktif) {
            opsi.setEnabled(true);
    }   
        for (JComponent opsi : opsiNoAktif){
            opsi.setEnabled(false);
        }
        
        
    }//GEN-LAST:event_burgerMouseClicked

    private void kopiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kopiMouseClicked
        JComponent[] opsiaktif = {opsi1,Opsi2,Opsi3,Opsi4,Opsi5,Opsi6,Opsi7,Opsi8,Opsi9,Opsi10,Opsi11};
        JComponent[] opsiNoAktif = {Opsi12};
        for(JComponent opsi : opsiaktif){
            opsi.setEnabled(true);
        }
        for(JComponent opsi : opsiNoAktif){
            opsi.setEnabled(false);
        }
    }//GEN-LAST:event_kopiMouseClicked

    private void jussMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jussMouseClicked
        JComponent[] opsiaktif = {opsi1, Opsi2, Opsi3, Opsi4, Opsi5, Opsi6, Opsi7, Opsi8, Opsi9};
        JComponent[] opsiNoAktif = {Opsi10,Opsi11,Opsi12};
        for (JComponent opsi : opsiaktif) {
            opsi.setEnabled(true);
    }   
        for (JComponent opsi : opsiNoAktif){
            opsi.setEnabled(false);
        }       
    }//GEN-LAST:event_jussMouseClicked

    private void friedChickenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_friedChickenMouseClicked
        JComponent[] opsiaktif = {opsi1, Opsi2, Opsi3, Opsi4, Opsi5, Opsi6};
        JComponent[] opsiNoAktif = { Opsi7, Opsi8, Opsi9,Opsi10,Opsi11,Opsi12};
        for (JComponent opsi : opsiaktif) {
            opsi.setEnabled(true);
    }   
        for (JComponent opsi : opsiNoAktif){
            opsi.setEnabled(false);
        }
    }//GEN-LAST:event_friedChickenMouseClicked

    private void friedFriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_friedFriesMouseClicked
        JComponent[] opsiaktif = {opsi1, Opsi2, Opsi3, Opsi4, Opsi5, Opsi6};
        JComponent[] opsiNoAktif = { Opsi7, Opsi8, Opsi9,Opsi10,Opsi11,Opsi12};
        for (JComponent opsi : opsiaktif) {
            opsi.setEnabled(true);
    }   
        for (JComponent opsi : opsiNoAktif){
            opsi.setEnabled(false);
        }
    }//GEN-LAST:event_friedFriesMouseClicked

    private void pizzaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pizzaMouseClicked
        JComponent[] opsiaktif = {opsi1, Opsi2, Opsi3, Opsi4, Opsi5, Opsi6,Opsi7, Opsi8, Opsi9};
        JComponent[] opsiNoAktif = {Opsi10,Opsi11,Opsi12};
        for (JComponent opsi : opsiaktif) {
            opsi.setEnabled(true);
    }   
        for (JComponent opsi : opsiNoAktif){
            opsi.setEnabled(false);
        }
    }//GEN-LAST:event_pizzaMouseClicked

    private void mieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mieMouseClicked
        JComponent[] opsiaktif = {opsi1, Opsi2, Opsi3, Opsi4, Opsi5, Opsi6,Opsi7, Opsi8, Opsi9};
        JComponent[] opsiNoAktif = {Opsi10,Opsi11,Opsi12};
        for (JComponent opsi : opsiaktif) {
            opsi.setEnabled(true);
    }   
        for (JComponent opsi : opsiNoAktif){
            opsi.setEnabled(false);
        }
    }//GEN-LAST:event_mieMouseClicked

    private void nasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nasiMouseClicked
        JComponent[] opsiaktif = {opsi1, Opsi2, Opsi3};
        JComponent[] opsiNoAktif = {Opsi4, Opsi5, Opsi6,Opsi7, Opsi8, Opsi9,Opsi10,Opsi11,Opsi12};
        for (JComponent opsi : opsiaktif) {
            opsi.setEnabled(true);
    }   
        for (JComponent opsi : opsiNoAktif){
            opsi.setEnabled(false);
        }
    }//GEN-LAST:event_nasiMouseClicked

    private void sodaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sodaMouseClicked
        JComponent[] opsiaktif = {opsi1, Opsi2, Opsi3,Opsi4, Opsi5, Opsi6};
        JComponent[] opsiNoAktif = {Opsi7, Opsi8, Opsi9,Opsi10,Opsi11,Opsi12};
        for (JComponent opsi : opsiaktif) {
            opsi.setEnabled(true);
    }   
        for (JComponent opsi : opsiNoAktif){
            opsi.setEnabled(false);
        }
    }//GEN-LAST:event_sodaMouseClicked

    private void kopiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kopiActionPerformed
        namaMenu.setText("Coffe");
        
//        MENENTUKAN OPSI
        opsi1.setText("Large");
        Opsi2.setText("Medium");
        Opsi3.setText("Small");
        Opsi4.setText("Latte");
        Opsi5.setText("Americano");
        Opsi6.setText("Capuccino");
        Opsi7.setText("Sugar");
        Opsi8.setText("Less Sugar");
        Opsi9.setText("No Sugar");
        Opsi10.setText("Ice");
        Opsi11.setText("Hot");
        
        dataPembeliaktif();
        bersihkanOpsi();
    }//GEN-LAST:event_kopiActionPerformed

    private void burgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_burgerActionPerformed
        
        opsi1.setText("Large");
        Opsi2.setText("Medium");
        Opsi3.setText("Small");
        Opsi4.setText("Saus Tomat");
        Opsi5.setText("Saus Pedas");
        Opsi6.setText("Saus Jamur");
        Opsi7.setText("Daging");
        Opsi8.setText("Tomat");
        Opsi9.setText("Sayuran Lainnya");
        namaMenu.setText("Burger");
        dataPembeliaktif();
        bersihkanOpsi();
    }//GEN-LAST:event_burgerActionPerformed

    private void opsi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opsi1ActionPerformed
        menu.setHargaMenu(Double.parseDouble(jumlahBeli.getText()));
        
        menu.setPilihMenu(namaMenu.getText()); // Mengatur pilihan menu berdasarkan nilai dari namaMenu
        menu.setPilihSize("Large"); // Mengatur ukuran menu menjadi "Large"
        menu.setSeleksiMenu(); // Menghitung harga berdasarkan pilihan menu dan ukuran yang ditetapkan
        harga.setText(Integer.toString((int) menu.getTotalSementara()));
    }//GEN-LAST:event_opsi1ActionPerformed

    private void Opsi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opsi2ActionPerformed
      
        
        menu.setHargaMenu(Double.parseDouble(jumlahBeli.getText()));
        
        menu.setPilihMenu(namaMenu.getText()); // Mengatur pilihan menu berdasarkan nilai dari namaMenu
        menu.setPilihSize("Medium"); // Mengatur ukuran menu menjadi "Large"
        menu.setSeleksiMenu(); // Menghitung harga berdasarkan pilihan menu dan ukuran yang ditetapkan
        harga.setText(Integer.toString((int) menu.getTotalSementara()));
        
    }//GEN-LAST:event_Opsi2ActionPerformed

    private void Opsi3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opsi3ActionPerformed
        
        
        menu.setHargaMenu(Double.parseDouble(jumlahBeli.getText()));
        
        menu.setPilihMenu(namaMenu.getText()); // Mengatur pilihan menu berdasarkan nilai dari namaMenu
        menu.setPilihSize("Small"); // Mengatur ukuran menu menjadi "Large"
        menu.setSeleksiMenu(); // Menghitung harga berdasarkan pilihan menu dan ukuran yang ditetapkan
        harga.setText(Integer.toString((int) menu.getTotalSementara()));
    }//GEN-LAST:event_Opsi3ActionPerformed

    private void opsi1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_opsi1FocusLost

    }//GEN-LAST:event_opsi1FocusLost

    private void jussActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jussActionPerformed
        namaMenu.setText("Juice");
        opsi1.setText("Large");
        Opsi2.setText("Medium");
        Opsi3.setText("Small");
        Opsi4.setText("Sugar");
        Opsi5.setText("Less Sugar");
        Opsi6.setText("No Sugar");
        Opsi7.setText("Jeruk");
        Opsi8.setText("Apel");
        Opsi9.setText("Mix Berry");
        bersihkanOpsi();
        dataPembeliaktif();
    }//GEN-LAST:event_jussActionPerformed

    private void friedChickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_friedChickenActionPerformed
        namaMenu.setText("Fried Chicken");
        opsi1.setText("Dada");
        Opsi2.setText("Paha");
        Opsi3.setText("Sayap");
        Opsi4.setText("Saus Tomat");
        Opsi5.setText("Saus Pedas");
        Opsi6.setText("Saus Jamur");
        bersihkanOpsi();
        dataPembeliaktif();
    }//GEN-LAST:event_friedChickenActionPerformed

    private void friedFriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_friedFriesActionPerformed
        namaMenu.setText("Fried Fries");
        opsi1.setText("Large");
        Opsi2.setText("Medium");
        Opsi3.setText("Small");
        Opsi4.setText("Saus Tomat");
        Opsi5.setText("Saus Pedas");
        Opsi6.setText("Saus Jamur");
        
        dataPembeliaktif();
        bersihkanOpsi();
    }//GEN-LAST:event_friedFriesActionPerformed

    private void pizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pizzaActionPerformed
        namaMenu.setText("Pizza");
        opsi1.setText("Large");
        Opsi2.setText("Medium");
        Opsi3.setText("Small");
        Opsi4.setText("Saus Tomat");
        Opsi5.setText("Saus Pedas");
        Opsi6.setText("Keju");
        Opsi7.setText("Sosis");
        Opsi8.setText("Tomat");
        Opsi9.setText("Sayuran Lainnya");
        
        dataPembeliaktif();
        bersihkanOpsi();
    }//GEN-LAST:event_pizzaActionPerformed

    private void mieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mieActionPerformed
        namaMenu.setText("Mie");
        opsi1.setText("Large");
        Opsi2.setText("Medium");
        Opsi3.setText("Small");
        Opsi4.setText("Saus Tomat");
        Opsi5.setText("Saus Pedas");
        Opsi6.setText("Saus Jamur");
        Opsi7.setText("Daging");
        Opsi8.setText("Tomat");
        Opsi9.setText("Sayuran Lainnya");
        
        dataPembeliaktif();
        bersihkanOpsi();
    }//GEN-LAST:event_mieActionPerformed

    private void nasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nasiActionPerformed
        namaMenu.setText("Nasi");
        
        opsi1.setText("Large");
        Opsi2.setText("Medium");
        Opsi3.setText("Small");
        
        dataPembeliaktif();
        bersihkanOpsi();
    }//GEN-LAST:event_nasiActionPerformed

    private void sodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sodaActionPerformed
        namaMenu.setText("Soda");
        
        opsi1.setText("Large");
        Opsi2.setText("Medium");
        Opsi3.setText("Small");
        Opsi4.setText("Sprite");
        Opsi5.setText("Cola");
        Opsi6.setText("Nipis Madu");
        
        dataPembeliaktif();
        bersihkanOpsi();
    }//GEN-LAST:event_sodaActionPerformed

    private void kopiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kopiKeyPressed
        
    }//GEN-LAST:event_kopiKeyPressed

    private void jumlahBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahBeliActionPerformed
 
    }//GEN-LAST:event_jumlahBeliActionPerformed

    private void jumlahBeliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlahBeliKeyPressed
        
    }//GEN-LAST:event_jumlahBeliKeyPressed

    private void buttonOpsiSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOpsiSelesaiActionPerformed
    nonaktif();
    disablemenu();
    konfirmasiPembayaranAktif();
    
    }//GEN-LAST:event_buttonOpsiSelesaiActionPerformed

    private void opsi1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_opsi1KeyPressed

    }//GEN-LAST:event_opsi1KeyPressed

    private void opsi1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opsi1MouseClicked

    }//GEN-LAST:event_opsi1MouseClicked

    private void Opsi2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Opsi2FocusLost
    
    }//GEN-LAST:event_Opsi2FocusLost

    private void opsi1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_opsi1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_opsi1FocusGained

    private void Opsi2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Opsi2KeyPressed
     
    }//GEN-LAST:event_Opsi2KeyPressed

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaActionPerformed

    private void jDonasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDonasiActionPerformed

    }//GEN-LAST:event_jDonasiActionPerformed

    private void pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembayaranActionPerformed
        
        
        
        menu.setPilihPembayaran(pembayaran.getSelectedItem().toString());
        menu.setSeleksiDiskon();
        diskon.setText(Double.toString(menu.getDiskon()));
        
        menu.setDonasi(Double.parseDouble(jDonasi.getText()));
        harga.setText(Integer.toString((int) menu.getTotalSementara()));
        ppn.setText(Integer.toString((int) menu.getPPN()));
        totalHarga.setText(Integer.toString((int) menu.getTotal()));
    }//GEN-LAST:event_pembayaranActionPerformed

    private void ppnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppnActionPerformed
      
    }//GEN-LAST:event_ppnActionPerformed

    private void bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarActionPerformed
        
        int x;
        x = JOptionPane.showConfirmDialog(null,"Bayar?","Konfirm", JOptionPane.YES_NO_OPTION);
        if(x==JOptionPane.YES_OPTION){
            menu.setHapus();
            bersih();
            bersihkanOpsi();
            nonaktif();
        }else{
            return;
        }
    }//GEN-LAST:event_bayarActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        int x;
        x = JOptionPane.showConfirmDialog(null,"Yakin mau keluar??","Konfirm", JOptionPane.YES_NO_OPTION);
        if(x==JOptionPane.YES_OPTION){
            dispose();
        }else{
            return;
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void buttonOpsiSelesaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buttonOpsiSelesaiKeyPressed
        
    }//GEN-LAST:event_buttonOpsiSelesaiKeyPressed

    private void bdonasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdonasiActionPerformed
        jDonasi.setEnabled(true);
    }//GEN-LAST:event_bdonasiActionPerformed

    private void noDonasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noDonasiActionPerformed
        jDonasi.setEnabled(false);
    }//GEN-LAST:event_noDonasiActionPerformed

    private void jumlahBeliMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jumlahBeliMousePressed
        
    }//GEN-LAST:event_jumlahBeliMousePressed

    private void jumlahBeliFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jumlahBeliFocusGained
       jumlahBeli.setText("");
    }//GEN-LAST:event_jumlahBeliFocusGained

    private void jumlahBeliFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jumlahBeliFocusLost
        
    }//GEN-LAST:event_jumlahBeliFocusLost

    private void jDonasiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jDonasiFocusGained
        jDonasi.setText("");
    }//GEN-LAST:event_jDonasiFocusGained

    private void jDonasiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jDonasiFocusLost

    }//GEN-LAST:event_jDonasiFocusLost

    private void jumlahBeliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jumlahBeliMouseClicked
        Size.clearSelection();
    }//GEN-LAST:event_jumlahBeliMouseClicked

    private void uangBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uangBayarActionPerformed
         
    }//GEN-LAST:event_uangBayarActionPerformed

    private void uangBayarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uangBayarMouseEntered
        
    }//GEN-LAST:event_uangBayarMouseEntered

    private void uangBayarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uangBayarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        menu.setBayar(Double.parseDouble(uangBayar.getText()));
        menu.setTotal(Double.parseDouble(totalHarga.getText()));
        
       
        kembalian.setText(Double.toString(menu.getTotalBayar()));
        
        if (menu.getBayar() < menu.getTotal() ) {
            JOptionPane.showMessageDialog(null, "Pembayaran Kurang!!", "Warning", JOptionPane.OK_OPTION);
            bayar.setEnabled(false);
            kembalian.setText("");
            uangBayar.setText("");
        }else{
            bayar.setEnabled(true);
        }
        
    }
    }//GEN-LAST:event_uangBayarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Opsi10;
    private javax.swing.JCheckBox Opsi11;
    private javax.swing.JCheckBox Opsi12;
    private javax.swing.JCheckBox Opsi2;
    private javax.swing.JCheckBox Opsi3;
    private javax.swing.JCheckBox Opsi4;
    private javax.swing.JCheckBox Opsi5;
    private javax.swing.JCheckBox Opsi6;
    private javax.swing.JCheckBox Opsi7;
    private javax.swing.JCheckBox Opsi8;
    private javax.swing.JCheckBox Opsi9;
    private javax.swing.ButtonGroup Size;
    private javax.swing.JButton bayar;
    private javax.swing.JRadioButton bdonasi;
    private javax.swing.JButton burger;
    private javax.swing.JButton buttonOpsiSelesai;
    private javax.swing.JTextField diskon;
    private javax.swing.ButtonGroup donasi;
    private javax.swing.JButton friedChicken;
    private javax.swing.JButton friedFries;
    private javax.swing.JTextField harga;
    private javax.swing.JButton jButton13;
    private javax.swing.JTextField jDonasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jumlahBeli;
    private javax.swing.JButton juss;
    private javax.swing.JTextField kembalian;
    private javax.swing.JButton kopi;
    private javax.swing.JButton mie;
    private javax.swing.JTextField namaMenu;
    private javax.swing.JTextField namaPembeli;
    private javax.swing.JButton nasi;
    private javax.swing.JRadioButton noDonasi;
    private javax.swing.JCheckBox opsi1;
    private javax.swing.JComboBox<String> pembayaran;
    private javax.swing.JButton pizza;
    private javax.swing.JTextField ppn;
    private javax.swing.JButton soda;
    private javax.swing.JTextField totalHarga;
    private javax.swing.JTextField uangBayar;
    // End of variables declaration//GEN-END:variables
}
